# Generated by Django 6.1 on 2026-08-29 22:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Centro',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre Institucional')),
                ('direccion', models.CharField(blank=True, default='', max_length=255, verbose_name='Dirección')),
                ('telefono', models.CharField(blank=True, default='', max_length=50, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, default='', max_length=150, verbose_name='Email Institucional')),
                ('logo', models.TextField(blank=True, null=True, verbose_name='URL o Base64 del Logo')),
                ('horarios_atencion', models.JSONField(blank=True, default=dict, verbose_name='Horarios de Atención Semanal')),
                ('configuracion', models.JSONField(blank=True, default=dict, verbose_name='Configuración y Políticas del Gabinete')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración del Centro Psicológico',
                'verbose_name_plural': 'Configuraciones del Centro',
            },
        ),
    ]
