# Generated by Django 6.1.1 on 2026-09-17 05:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan', models.CharField(max_length=50, verbose_name='Plan de Suscripción')),
                ('email_cliente', models.EmailField(max_length=150, verbose_name='Email del Cliente')),
                ('nombre_centro', models.CharField(max_length=150, verbose_name='Nombre del Centro')),
                ('nombre_admin', models.CharField(default='Administrador', max_length=100, verbose_name='Nombre del Administrador')),
                ('stripe_session_id', models.CharField(max_length=255, unique=True, verbose_name='Stripe Session ID')),
                ('stripe_customer_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Stripe Customer ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de Pago'), ('activa', 'Activa'), ('cancelada', 'Cancelada'), ('expirada', 'Expirada')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_activacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Activación')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suscripciones', to='tenants.tenant', verbose_name='Centro (Tenant)')),
            ],
            options={
                'verbose_name': 'Suscripción',
                'verbose_name_plural': 'Suscripciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
