# Generated by Django 6.1.1 on 2026-09-17 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suscripcion',
            name='password_temporal',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Contraseña Temporal Inicial'),
        ),
    ]
