# Generated by Django 6.1 on 2026-09-06 08:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_paciente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField()),
                ('duracion_minutos', models.PositiveIntegerField(default=60)),
                ('estado', models.CharField(choices=[('reservada', 'Reservada'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('reprogramada', 'Reprogramada'), ('inasistencia', 'Inasistencia')], default='reservada', max_length=20)),
                ('motivo', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='users.paciente')),
                ('psicologo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='users.psicologo')),
            ],
            options={
                'ordering': ['-fecha_hora'],
                'indexes': [models.Index(fields=['psicologo', 'fecha_hora'], name='users_cita_psicolo_8b306d_idx'), models.Index(fields=['paciente', 'fecha_hora'], name='users_cita_pacient_325e6f_idx')],
            },
        ),
    ]
