# Generated by Django 6.1 on 2026-09-06 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_cu10_alertas_cu13_teleconsultas'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='modalidad',
            field=models.CharField(choices=[('presencial', 'Presencial'), ('virtual', 'Virtual')], default='presencial', max_length=10),
        ),
    ]
