# Generated by Django 6.1 on 2026-09-06 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_cita_modalidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracioncentro',
            name='direccion',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='configuracioncentro',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='configuracioncentro',
            name='especialidades',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='configuracioncentro',
            name='horarios_atencion',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='configuracioncentro',
            name='linea_crisis',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='configuracioncentro',
            name='modalidad',
            field=models.CharField(blank=True, default='Presencial', max_length=60),
        ),
        migrations.AddField(
            model_name='configuracioncentro',
            name='nif_rif',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='configuracioncentro',
            name='nombre',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='configuracioncentro',
            name='registro_sanitario',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='configuracioncentro',
            name='telefono',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='configuracioncentro',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='configuracioncentro',
            name='primary_color',
            field=models.CharField(default='#235d55', max_length=7),
        ),
    ]
