# Generated by Django 6.1 on 2026-09-06 21:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha', models.DateField(verbose_name='Fecha de la Cita')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de Inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora de Finalización')),
                ('modalidad', models.CharField(choices=[('PRESENCIAL', 'Presencial'), ('VIRTUAL', 'Virtual (Teleconsulta)')], default='PRESENCIAL', max_length=20, verbose_name='Modalidad')),
                ('estado', models.CharField(choices=[('PROGRAMADA', 'Programada'), ('CONFIRMADA', 'Confirmada'), ('REALIZADA', 'Realizada'), ('CANCELADA', 'Cancelada'), ('INASISTENCIA', 'Inasistencia / Ausente')], default='PROGRAMADA', max_length=25, verbose_name='Estado de la Cita')),
                ('motivo_consulta', models.TextField(blank=True, default='', verbose_name='Motivo de Consulta')),
                ('costo', models.DecimalField(decimal_places=2, default=150.0, max_digits=10, verbose_name='Costo de la Sesión (BOB)')),
                ('motivo_cancelacion', models.TextField(blank=True, default='', verbose_name='Motivo de Cancelación')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='citas', to='clinica.paciente')),
                ('psicologo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='citas', to='clinica.psicologo')),
            ],
            options={
                'verbose_name': 'Cita Clínica',
                'verbose_name_plural': 'Citas Clínicas',
                'db_table': 'agenda_cita',
                'ordering': ['fecha', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Teleconsulta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sala_id', models.CharField(max_length=150, unique=True, verbose_name='Identificador Único de Sala Jitsi')),
                ('jwt_room_token', models.TextField(blank=True, null=True, verbose_name='Token JWT de Acceso WebRTC')),
                ('hora_inicio_real', models.DateTimeField(blank=True, null=True, verbose_name='Hora Inicio Efectiva')),
                ('hora_fin_real', models.DateTimeField(blank=True, null=True, verbose_name='Hora Fin Efectiva')),
                ('duracion_segundos', models.IntegerField(default=0, verbose_name='Duración Total (segundos)')),
                ('cita', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teleconsulta', to='agenda.cita')),
            ],
            options={
                'verbose_name': 'Teleconsulta WebRTC',
                'verbose_name_plural': 'Teleconsultas WebRTC',
                'db_table': 'agenda_teleconsulta',
            },
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('INASISTENCIA_REITERADA', 'Inasistencia Reiterada'), ('RIESGO_DESERCION', 'Riesgo de Deserción Terapéutica'), ('URGENCIA_CLINICA', 'Urgencia Clínica')], max_length=50, verbose_name='Tipo de Alerta')),
                ('severidad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], default='MEDIA', max_length=20, verbose_name='Severidad')),
                ('descripcion', models.TextField(verbose_name='Descripción de la Alerta')),
                ('resuelta', models.BooleanField(default=False, verbose_name='¿Resuelta?')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Resolución')),
                ('nota_resolucion', models.TextField(blank=True, default='', verbose_name='Nota de Resolución Clínica')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='clinica.paciente')),
            ],
            options={
                'verbose_name': 'Alerta Clínica',
                'verbose_name_plural': 'Alertas Clínicas',
                'db_table': 'agenda_alerta',
                'ordering': ['resuelta', '-fecha_creacion'],
                'indexes': [models.Index(fields=['paciente', 'resuelta'], name='idx_alerta_paciente_resuelta'), models.Index(fields=['tipo'], name='idx_alerta_tipo')],
            },
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['psicologo', 'fecha', 'hora_inicio'], name='idx_cita_psico_fecha_hora'),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['paciente', 'fecha'], name='idx_cita_paciente_fecha'),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['estado'], name='idx_cita_estado'),
        ),
        migrations.AddConstraint(
            model_name='cita',
            constraint=models.CheckConstraint(condition=models.Q(('hora_fin__gt', models.F('hora_inicio'))), name='chk_cita_rango_horario'),
        ),
        migrations.AddConstraint(
            model_name='cita',
            constraint=models.CheckConstraint(condition=models.Q(('costo__gte', 0)), name='chk_cita_costo_no_negativo'),
        ),
        migrations.AddIndex(
            model_name='teleconsulta',
            index=models.Index(fields=['sala_id'], name='idx_teleconsulta_sala'),
        ),
    ]
