# Generated by Django 6.1.1 on 2026-10-04 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerta',
            name='tipo',
            field=models.CharField(choices=[('INASISTENCIA_REITERADA', 'Inasistencia Reiterada'), ('RIESGO_DESERCION', 'Riesgo de Deserción Terapéutica'), ('URGENCIA_CLINICA', 'Urgencia Clínica'), ('CRISIS_RETROCESO', 'Retroceso / Factor de Crisis')], max_length=50, verbose_name='Tipo de Alerta'),
        ),
    ]
