# Generated by Django 6.1 on 2026-08-29 22:19

import django.db.models.deletion
import django_tenants.postgresql_backend.base
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150, unique=True, verbose_name='Nombre del Centro')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Identificador Slug')),
                ('direccion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección')),
                ('telefono', models.CharField(blank=True, max_length=30, null=True, verbose_name='Teléfono')),
                ('email_contacto', models.EmailField(blank=True, max_length=150, null=True, verbose_name='Email de Contacto')),
                ('plan', models.CharField(default='PRO', max_length=50, verbose_name='Plan de Suscripción')),
                ('activo', models.BooleanField(default=True, verbose_name='Estado Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Centro Psicológico (Tenant)',
                'verbose_name_plural': 'Centros Psicológicos (Tenants)',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Dominio',
            fields=[
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Dominio de Centro',
                'verbose_name_plural': 'Dominios de Centros',
            },
        ),
    ]
