# Generated by Django 6.1.1 on 2026-10-04 22:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupRegistro',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('archivo', models.CharField(max_length=255, verbose_name='Nombre de Archivo')),
                ('sha256', models.CharField(max_length=64, verbose_name='Checksum SHA-256')),
                ('tamano', models.BigIntegerField(default=0, verbose_name='Tamaño en Bytes')),
                ('tamano_mb', models.FloatField(default=0.0, verbose_name='Tamaño en MB')),
                ('ambito', models.CharField(default='TENANT', max_length=50, verbose_name='Ámbito (GLOBAL o TENANT)')),
                ('schema_name', models.CharField(default='public', max_length=100, verbose_name='Esquema de BD')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Generación')),
                ('origen', models.CharField(default='MANUAL', max_length=50, verbose_name='Origen (MANUAL o CRON)')),
                ('estado', models.CharField(default='COMPLETADO', max_length=50, verbose_name='Estado')),
                ('url_descarga', models.CharField(blank=True, max_length=255, null=True, verbose_name='URL de Descarga')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backups', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Registro de Copia de Seguridad',
                'verbose_name_plural': 'Registros de Copias de Seguridad',
                'db_table': 'backups_registro',
                'ordering': ['-fecha'],
            },
        ),
    ]
