# Generated by Django 6.1 on 2026-09-06 21:50

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de Especialidad')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Especialidad Clínica',
                'verbose_name_plural': 'Especialidades Clínicas',
                'db_table': 'clinica_especialidad',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Psicologo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_colegiado', models.CharField(max_length=50, unique=True, verbose_name='Número de Colegiado')),
                ('biografia', models.TextField(blank=True, default='', verbose_name='Biografía / Perfil Profesional')),
                ('modalidad', models.CharField(choices=[('PRESENCIAL', 'Presencial'), ('VIRTUAL', 'Virtual'), ('MIXTA', 'Mixta (Presencial y Virtual)')], default='MIXTA', max_length=20, verbose_name='Modalidad')),
                ('tarifa_base', models.DecimalField(decimal_places=2, default=150.0, max_digits=10, verbose_name='Tarifa Base (BOB)')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo en el Centro')),
                ('fecha_ingreso', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Incorporación')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_psicologo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Psicólogo / Terapeuta',
                'verbose_name_plural': 'Psicólogos',
                'db_table': 'clinica_psicologo',
                'ordering': ['usuario__nombre', 'usuario__apellido'],
            },
        ),
        migrations.CreateModel(
            name='PsicologoEspecialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.especialidad')),
                ('psicologo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.psicologo')),
            ],
            options={
                'verbose_name': 'Especialidad de Psicólogo',
                'verbose_name_plural': 'Especialidades de Psicólogos',
                'db_table': 'clinica_psicologo_especialidad',
                'unique_together': {('psicologo', 'especialidad')},
            },
        ),
        migrations.AddField(
            model_name='psicologo',
            name='especialidades',
            field=models.ManyToManyField(blank=True, related_name='psicologos', through='clinica.PsicologoEspecialidad', to='clinica.especialidad'),
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo_expediente', models.CharField(max_length=30, unique=True, verbose_name='Código de Expediente')),
                ('ci', models.CharField(max_length=20, unique=True, verbose_name='Cédula de Identidad (CI)')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1, verbose_name='Género')),
                ('contacto_emergencia_nombre', models.CharField(blank=True, default='', max_length=120, verbose_name='Contacto Emergencia (Nombre)')),
                ('contacto_emergencia_telf', models.CharField(blank=True, default='', max_length=25, verbose_name='Contacto Emergencia (Teléfono)')),
                ('tutor_legal_nombre', models.CharField(blank=True, default='', max_length=120, verbose_name='Tutor Legal (Nombre)')),
                ('tutor_legal_ci', models.CharField(blank=True, default='', max_length=20, verbose_name='Tutor Legal (CI)')),
                ('fecha_registro', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Registro Clínico')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_paciente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'db_table': 'clinica_paciente',
                'ordering': ['-fecha_registro', 'usuario__nombre'],
                'indexes': [models.Index(fields=['ci'], name='idx_paciente_ci'), models.Index(fields=['codigo_expediente'], name='idx_paciente_expediente')],
            },
        ),
        migrations.CreateModel(
            name='Disponibilidad',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dia_semana', models.SmallIntegerField(choices=[(0, 'Domingo'), (1, 'Lunes'), (2, 'Martes'), (3, 'Miércoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sábado')], verbose_name='Día de la Semana (0-6)')),
                ('hora_inicio', models.TimeField(verbose_name='Hora Inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora Fin')),
                ('duracion_bloque_min', models.SmallIntegerField(default=50, verbose_name='Duración Bloque (min)')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('psicologo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades', to='clinica.psicologo')),
            ],
            options={
                'verbose_name': 'Disponibilidad Horaria',
                'verbose_name_plural': 'Disponibilidades Horarias',
                'db_table': 'clinica_disponibilidad',
                'ordering': ['dia_semana', 'hora_inicio'],
                'indexes': [models.Index(fields=['psicologo', 'dia_semana'], name='idx_disp_psico_dia')],
                'constraints': [models.CheckConstraint(condition=models.Q(('hora_fin__gt', models.F('hora_inicio'))), name='chk_disponibilidad_rango_horario'), models.CheckConstraint(condition=models.Q(('duracion_bloque_min__gt', 0)), name='chk_disponibilidad_bloque_pos')],
            },
        ),
        migrations.AddIndex(
            model_name='psicologo',
            index=models.Index(fields=['numero_colegiado'], name='idx_psicologo_colegiado'),
        ),
    ]
