# Generated by Django 6.1 on 2026-09-06 21:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='fecha_registro',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Fecha de Registro Clínico'),
        ),
        migrations.AlterField(
            model_name='psicologo',
            name='fecha_ingreso',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Fecha de Incorporación'),
        ),
    ]
