# Generated by Django 6.1.1 on 2026-10-04 16:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0003_consentimientoinformado_formulariopreconsulta_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversacionChatbot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(db_index=True, max_length=128, verbose_name='ID de Sesión Web/Móvil')),
                ('estado', models.CharField(choices=[('BOT_ACTIVO', 'Bot Activo'), ('ESCALADA_HUMANO', 'Escalada a Recepción Humana'), ('EN_ATENCION', 'En Atención por Operador'), ('FINALIZADA', 'Conversación Finalizada')], default='BOT_ACTIVO', max_length=30, verbose_name='Estado de la Conversación')),
                ('nivel_riesgo', models.CharField(choices=[('NORMAL', 'Normal'), ('MODERADO', 'Moderado'), ('CRISIS', 'Crisis / Alerta Inminente')], default='NORMAL', max_length=20, verbose_name='Nivel de Riesgo Detectado')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Inicio')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actividad')),
                ('operador_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chats_operados', to=settings.AUTH_USER_MODEL, verbose_name='Operador Asignado')),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversaciones_chatbot', to='clinica.paciente', verbose_name='Paciente')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversaciones_chatbot', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Autenticado')),
            ],
            options={
                'verbose_name': 'Conversación de Chatbot',
                'verbose_name_plural': 'Conversaciones de Chatbot',
                'db_table': 'clinica_conversacion_chatbot',
                'ordering': ['-fecha_actualizacion'],
            },
        ),
        migrations.CreateModel(
            name='MensajeChatbot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('remitente', models.CharField(choices=[('BOT', 'Asistente Bot'), ('USUARIO', 'Usuario / Paciente'), ('OPERADOR', 'Recepcionista Humano')], max_length=20, verbose_name='Remitente')),
                ('texto', models.TextField(verbose_name='Contenido del Mensaje')),
                ('es_alerta_crisis', models.BooleanField(default=False, verbose_name='Alerta de Riesgo Vital / Crisis')),
                ('opciones_sugeridas', models.JSONField(blank=True, default=list, verbose_name='Opciones Rápidas')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Marca Temporal')),
                ('conversacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='clinica.conversacionchatbot', verbose_name='Conversación')),
            ],
            options={
                'verbose_name': 'Mensaje de Chatbot',
                'verbose_name_plural': 'Mensajes de Chatbot',
                'db_table': 'clinica_mensaje_chatbot',
                'ordering': ['timestamp'],
            },
        ),
    ]
