# Generated by Django 6.1.1 on 2026-10-05 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0004_conversacionchatbot_mensajechatbot'),
    ]

    operations = [
        migrations.AddField(
            model_name='firmaconsentimiento',
            name='fecha_revocacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Revocación'),
        ),
        migrations.AddField(
            model_name='firmaconsentimiento',
            name='motivo_revocacion',
            field=models.TextField(blank=True, default='', verbose_name='Motivo de Revocación'),
        ),
        migrations.AddField(
            model_name='firmaconsentimiento',
            name='revocado',
            field=models.BooleanField(default=False, verbose_name='Firma Revocada'),
        ),
    ]
