# Generated by Django 6.1.1 on 2026-10-06 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0005_firmaconsentimiento_fecha_revocacion_and_more'),
        ('clinica', '0005_hu33_closure_details'),
    ]

    operations = [
    ]
